<a href="https://colab.research.google.com/github/KombatBakpen/Deep-Learning-with-Pytorch-/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors are simply like numpy arrays; python list:**

**Why tensors over numpy arrays?**
*Tensors are used instead of NumPy arrays because tensors provide support for high-dimensional data and operations, making them more suitable for deep learning frameworks like TensorFlow and PyTorch. Additionally, tensors offer GPU acceleration and seamless integration with deep learning libraries, enabling efficient computation and optimization of neural network models.*

source: https://python.plainenglish.io/numpy-arrays-vs-tensorflow-tensors-95a9c39e1c17


In [11]:
import torch
import numpy as np


**Overview of Python LISTS**

In [3]:
my_list = [1,2,3,4,5,], [6,7,8,9,10]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

**Overview of Numpy ARRAYS**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.73483128, 0.98367334, 0.57526318, 0.77473989],
       [0.95413288, 0.75950488, 0.09911914, 0.05074579],
       [0.33763851, 0.50311232, 0.36245873, 0.85521975]])

In [6]:
np1.dtype # but note tensor's datatype is flaot32

dtype('float64')

# ***TENSORS***

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0877, -0.1634,  0.3979,  0.6247],
        [-0.3170,  0.6583, -0.3308, -2.1942],
        [ 0.4228,  1.3802, -0.5299,  0.6957]])

In [8]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.randn(2, 3, 4)
tensor_3d # 3d tensor; again just similar to a numpy 3d array

tensor([[[-1.1251, -0.9697,  2.0778, -0.4076],
         [ 0.8747,  0.9662,  0.7365,  0.1910],
         [ 0.2740, -0.8876,  0.0376, -0.2508]],

        [[-0.1728, -0.6266,  1.3161,  1.8212],
         [-0.8769,  0.3254, -0.1649, -1.4000],
         [-0.8701,  0.1959,  0.2320,  0.6125]]])

In [10]:
# converting a numpy arrays into tensor
# NB = the default datatype is still the numpy array;
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7348, 0.9837, 0.5753, 0.7747],
        [0.9541, 0.7595, 0.0991, 0.0507],
        [0.3376, 0.5031, 0.3625, 0.8552]], dtype=torch.float64)

# **TENSOR OPERATIONS**

In [13]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Reshape and View**
Reshape takes the tensor and convert to the matrix order in which you specify. You have to make use the order you're entering will fit the size of the tensor. View and reshape perform the same functions



In [14]:
#reshape
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# reshape if we don't know the number of items. this is done using -1
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [21]:
# View
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch4


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
#changing the items in the list
my_torch3[1] = 20
my_torch3


tensor([ 0, 20,  2,  3,  4,  5,  6,  7,  8,  9])

In [23]:
my_torch3

tensor([ 0, 20,  2,  3,  4,  5,  6,  7,  8,  9])

**NB**: When you make a change with reshape and view that change will get reflected everywhere.

**Slices**
Allows you to get a section of the data

In [27]:
my_torch5 = torch.arange(10)
# grab an item in a specific location
my_torch5[6]

tensor(6)

In [29]:
# grab a slice: that is range of items in specific locations
my_torch5[7]

tensor(7)

In [36]:
# returning columns and rows
#row

my_torch6 = my_torch5.reshape(5,2)
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [37]:
# column
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# **TENSOR ARITHMETIC**
1. Add, subtract, mutiply, divide,remainders, exponents
2. Shorthand and longhand
3. Reassignment









In [38]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])


**Addition**

In [39]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [40]:
# the more pytorchic way, ahahahahah; aka, longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [59]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

**Subtraction**

In [42]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [43]:
torch.subtract(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

**Multiplication**


In [44]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [45]:
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [60]:
tensor_a.multiply(tensor_b)

tensor([ 5, 12, 21, 32])

**Division**

In [46]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [47]:
torch.divide(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [61]:
tensor_b.divide(tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

**Remainders**

In [49]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [50]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [62]:
tensor_b.remainder(tensor_a)

tensor([0, 0, 1, 0])

**Exponents**

In [55]:
tensor_a**2

tensor([ 1,  4,  9, 16])

In [56]:
tensor_b**tensor_a

tensor([   5,   36,  343, 4096])

In [57]:
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [58]:
torch.pow(tensor_a, 2)

tensor([ 1,  4,  9, 16])

In [69]:
tensor_a.pow(3)

tensor([ 4096,  8000, 13824, 21952])

**Reassignment**

In [72]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([26, 32, 38, 44])

In [73]:
# we can do this reassignment in a special way
tensor_a.add_(tensor_b)

tensor([31, 38, 45, 52])